AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: notify-aws-cost

Parameters:
  ProjectName:
    Type: String
    Default: notify-aws-cost
  DiscordWebhookURL:
    Type: String

Globals:
  Function:
    Timeout: 10

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref ProjectName
      Description: !Ref ProjectName 
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment: 
        Variables:
          AWS_BUDGET_NAME: !Ref Budget
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookURL
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSBillingReadOnlyAccess
      Events:
        Scheduled:
          Type: ScheduleV2
          Properties:
            Name: !Sub "${ProjectName}-Schedule"
            ScheduleExpression: cron(5 0 * * ? *)
            State: ENABLED
      PropagateTags: true

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Function}"
      RetentionInDays: 30

  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub "${ProjectName}-CostBudget"
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: 50
          Unit: USD
        AutoAdjustData:
          AutoAdjustType: HISTORICAL
          HistoricalOptions:
              BudgetAdjustmentPeriod: 6
        CostTypes:
          IncludeCredit: false
          IncludeDiscount: true
          IncludeOtherSubscription: true
          IncludeRecurring: true
          IncludeRefund: false
          IncludeSubscription: true
          IncludeSupport: true
          IncludeTax: false
          IncludeUpfront: false
          UseAmortized: false
          UseBlended: false
