name: Cloudformation CI/CD
 
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
 
env: 
  TEMPLATE_FILE: template.yaml

jobs:
  CICD:
    runs-on: ubuntu-latest

    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3

      - name: Setup aws-sam
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Test
        id: test
        continue-on-error: true
        run: |
          pip install -r requirements.txt -q
          pytest -v tests/test_main.py
        env:
          AWS_BUDGET_NAME: "notify-aws-cost-CostBudget"
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_TEST }}
        working-directory: "./"

      - name: Build
        id: build
        if: steps.test.outcome == 'success'
        run: |
          pip install -r requirements.txt -q --target ./app
          sam build --use-container --config-env ${CONFIG_ENV} --template-file ${TEMPLATE_FILE} --parameter-overrides DiscordWebhookURL=${DISCORD_WEBHOOK_URL}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_PRD }}
        working-directory: "./"

      - name: Deploy
        if: steps.build.outcome == 'success'
        run: sam deploy --template-file ${TEMPLATE_FILE} --parameter-overrides DiscordWebhookURL=${DISCORD_WEBHOOK_URL}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_PRD }}
        working-directory: "./"
